"""price_cents_nullable

Revision ID: 51a9d9342626
Revises: e4926849947c
Create Date: 2026-03-25 15:56:02.682884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a9d9342626'
down_revision: Union[str, Sequence[str], None] = 'e4926849947c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'price_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'price_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
